name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - dev-ose
      - master
  pull_request:
    branches:
      - master
      - dev-ose

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: gradle/wrapper-validation-action@v1.0.5
