name: Create release
on:
  push:
    tags:
      - v*

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}

jobs:
  build:
    name: Create release
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}

      - name: Build signed package
        # Make sure that caches are disabled to generate reproducible release builds
        run: ./gradlew --no-build-cache --no-configuration-cache --no-daemon app:assembleRelease

      - name: Create Github release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ env.prerelease }}
          files: app/build/outputs/apk/ose/release/*.apk
          fail_on_unmatched_files: true
          generate_release_notes: true
          discussion_category_name: Announcements

      - name: cleanup
        run: ./signing/cleanup.sh
