name: Create release
on:
  push:
    tags:
      - '*'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

env:
  java-version: 21   # keep in sync with gradle/gradle-daemon-jvm.properties
  prerelease: ${{ contains(github.ref_name, '-alpha') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-rc') }}

jobs:
  build:
    name: Create release
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.java-version }}

      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}

      - name: Build signed package
        run: ./gradlew app:clean app-ose:assembleRelease

      - name: Create Github release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: ${{ env.prerelease }}
          files: app-ose/build/outputs/apk/ose/release/*.apk
          fail_on_unmatched_files: true
          generate_release_notes: true

      - name: cleanup
        run: ./signing/cleanup.sh
